/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "mjolnir.js",
  "tagline": "An event manager",
  "url": "https://visgl.github.io",
  "baseUrl": "/mjolnir.js/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "/favicon.png",
  "organizationName": "visgl",
  "projectName": "mjolnir.js",
  "trailingSlash": false,
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "../docs",
          "sidebarPath": "/Users/missx/Source/mjolnir.js/website/src/docs-sidebar.js",
          "editUrl": "https://github.com/visgl/mjolnir.js/tree/master/website"
        },
        "theme": {
          "customCss": [
            "/Users/missx/Source/mjolnir.js/website/src/styles.css"
          ]
        }
      }
    ]
  ],
  "plugins": [
    [
      "./ocular-docusaurus-plugin",
      {
        "debug": true,
        "resolve": {
          "modules": [
            "/Users/missx/Source/mjolnir.js/website/node_modules",
            "/Users/missx/Source/mjolnir.js/node_modules"
          ],
          "alias": {
            "mjolnir.js": "/Users/missx/Source/mjolnir.js/src"
          }
        },
        "plugins": [],
        "module": {
          "rules": [
            {
              "test": {},
              "resolve": {
                "fullySpecified": false
              }
            }
          ]
        }
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "examples",
        "path": "./src/examples",
        "routeBasePath": "examples",
        "sidebarPath": "/Users/missx/Source/mjolnir.js/website/src/examples-sidebar.js",
        "breadcrumbs": false,
        "docItemComponent": "/Users/missx/Source/mjolnir.js/website/src/components/example/doc-item-component.jsx"
      }
    ],
    [
      "/Users/missx/Source/mjolnir.js/website/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js",
      {}
    ],
    [
      "@docusaurus/plugin-client-redirects",
      {}
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "mjolnir.js",
      "logo": {
        "alt": "vis.gl Logo",
        "src": "images/visgl-logo-dark.png"
      },
      "items": [
        {
          "to": "/examples",
          "position": "left",
          "label": "Examples"
        },
        {
          "to": "/docs",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "https://medium.com/vis-gl",
          "label": "Blog",
          "position": "left"
        },
        {
          "href": "https://github.com/visgl/mjolnir.js",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Other vis.gl Libraries",
          "items": [
            {
              "label": "luma.gl",
              "href": "https://luma.gl"
            },
            {
              "label": "loaders.gl",
              "href": "https://loaders.gl"
            },
            {
              "label": "deck.gl",
              "href": "https:/deck.gl"
            },
            {
              "label": "vis.gl",
              "href": "https://vis.gl"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "vis.gl blog on Medium",
              "href": "https://medium.com/vis-gl"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/visgl/mjolnir.js"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2024 OpenJS Foundation"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#403f53",
          "backgroundColor": "#FBFBFB"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(72, 118, 214)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(152, 159, 177)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "builtin",
              "char",
              "constant",
              "url"
            ],
            "style": {
              "color": "rgb(72, 118, 214)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(201, 103, 101)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(170, 9, 130)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(153, 76, 195)"
            }
          },
          {
            "types": [
              "function",
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(153, 76, 195)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(17, 17, 17)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(153, 76, 195)"
            }
          },
          {
            "types": [
              "operator",
              "property",
              "keyword",
              "namespace"
            ],
            "style": {
              "color": "rgb(12, 150, 155)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(188, 84, 84)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#d6deeb",
          "backgroundColor": "#011627"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgba(239, 83, 80, 0.56)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted",
              "attr-name"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(99, 119, 119)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "rgb(173, 219, 103)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(214, 222, 235)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(255, 203, 139)"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "rgb(127, 219, 202)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "property"
            ],
            "style": {
              "color": "rgb(128, 203, 196)"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
