import { InputEvent, InputDirection } from './input-consts';
import type { Recognizer } from '../recognizer/recognizer';

export type Point = {x: number; y: number};
export type Vector = {x: number; y: number};
export type PointerEventLike = {clientX: number; clientY: number};

export type DeviceInputEvent = MouseEvent | PointerEvent;

/**
 * @private
 * Transitional type generated by Input classes for processing */
export type RawInput = {
  pointers: DeviceInputEvent[];
  changedPointers: DeviceInputEvent[];
  pointerType: string;
  srcEvent: DeviceInputEvent;
  eventType: InputEvent;

  // Populated during processing
  timeStamp?: number;
  deltaTime?: number;

  center?: Point;
  deltaX?: number;
  deltaY?: number;
  angle?: number;
  distance?: number;
  scale?: number;
  rotation?: number;
  
  direction?: InputDirection;
  offsetDirection?: InputDirection;
  
  velocity?: number;
  velocityX?: number;
  velocityY?: number;

  overallVelocity?: number;
  overallVelocityX?: number;
  overallVelocityY?: number;

  maxPointers?: number;
  target?: HTMLElement;

  additionalEvent?: string;

  // Internal flags
  isFirst?: boolean;
  isFinal?: boolean;
};

/**
 * @private
 * Simplified HammerInput object retained in memory to help event processing */
export type SimpleInput = {
  pointers: PointerEventLike[];
  timeStamp: number;
  center: Point;
  deltaX?: number;
  deltaY?: number;
}

/**
 * @private
 * Information about an input session (pointers down-move-up)
 */
export type Session = {
  pointerEvents?: PointerEvent[];
  stopped?: number;
  curRecognizer?: Recognizer<any>;
  offsetDelta?: Vector;
  prevDelta?: Vector;

  firstInput?: SimpleInput;
  firstMultiple?: SimpleInput | false;

  prevInput?: HammerInput;
  lastInterval?: HammerInput;

  prevented?: boolean;
};


/** 
 * @public 
 * Emitted input event */
export type HammerInput = Omit<Required<RawInput>, 'isFirst' | 'isFinal'> & {
  /** if emitted by TapRecognizer */
  tapCount?: number;
};
